/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from "@solana/web3.js";
import * as beetSolana from "@metaplex-foundation/beet-solana";
import * as beet from "@metaplex-foundation/beet";
import { MsAccountMeta, msAccountMetaBeet } from "../types/MsAccountMeta";

/**
 * Arguments used to create {@link MsInstruction}
 * @category Accounts
 * @category generated
 */
export type MsInstructionArgs = {
  programId: web3.PublicKey;
  keys: MsAccountMeta[];
  data: Uint8Array;
  instructionIndex: number;
  bump: number;
  executed: boolean;
};

export const msInstructionDiscriminator = [
  238, 185, 126, 149, 189, 89, 255, 92,
];
/**
 * Holds the data for the {@link MsInstruction} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class MsInstruction implements MsInstructionArgs {
  private constructor(
    readonly programId: web3.PublicKey,
    readonly keys: MsAccountMeta[],
    readonly data: Uint8Array,
    readonly instructionIndex: number,
    readonly bump: number,
    readonly executed: boolean
  ) {}

  /**
   * Creates a {@link MsInstruction} instance from the provided args.
   */
  static fromArgs(args: MsInstructionArgs) {
    return new MsInstruction(
      args.programId,
      args.keys,
      args.data,
      args.instructionIndex,
      args.bump,
      args.executed
    );
  }

  /**
   * Deserializes the {@link MsInstruction} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [MsInstruction, number] {
    return MsInstruction.deserialize(accountInfo.data, offset);
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link MsInstruction} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<MsInstruction> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    );
    if (accountInfo == null) {
      throw new Error(`Unable to find MsInstruction account at ${address}`);
    }
    return MsInstruction.fromAccountInfo(accountInfo, 0)[0];
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      "SMPLecH534NA9acpos4G6x7uf3LWbCAwZQE9e8ZekMu"
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, msInstructionBeet);
  }

  /**
   * Deserializes the {@link MsInstruction} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [MsInstruction, number] {
    return msInstructionBeet.deserialize(buf, offset);
  }

  /**
   * Serializes the {@link MsInstruction} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return msInstructionBeet.serialize({
      accountDiscriminator: msInstructionDiscriminator,
      ...this,
    });
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link MsInstruction} for the provided args.
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   */
  static byteSize(args: MsInstructionArgs) {
    const instance = MsInstruction.fromArgs(args);
    return msInstructionBeet.toFixedFromValue({
      accountDiscriminator: msInstructionDiscriminator,
      ...instance,
    }).byteSize;
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link MsInstruction} data from rent
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    args: MsInstructionArgs,
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      MsInstruction.byteSize(args),
      commitment
    );
  }

  /**
   * Returns a readable version of {@link MsInstruction} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      programId: this.programId.toBase58(),
      keys: this.keys,
      data: this.data,
      instructionIndex: this.instructionIndex,
      bump: this.bump,
      executed: this.executed,
    };
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const msInstructionBeet = new beet.FixableBeetStruct<
  MsInstruction,
  MsInstructionArgs & {
    accountDiscriminator: number[] /* size: 8 */;
  }
>(
  [
    ["accountDiscriminator", beet.uniformFixedSizeArray(beet.u8, 8)],
    ["programId", beetSolana.publicKey],
    ["keys", beet.array(msAccountMetaBeet)],
    ["data", beet.bytes],
    ["instructionIndex", beet.u8],
    ["bump", beet.u8],
    ["executed", beet.bool],
  ],
  MsInstruction.fromArgs,
  "MsInstruction"
);
