/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet';
import * as web3 from '@solana/web3.js';
import { IncomingInstruction, incomingInstructionBeet } from '../types/IncomingInstruction';

/**
 * @category Instructions
 * @category AddInstruction
 * @category generated
 */
export type AddInstructionInstructionArgs = {
    incomingInstruction: IncomingInstruction;
};
/**
 * @category Instructions
 * @category AddInstruction
 * @category generated
 */
export const addInstructionStruct = new beet.FixableBeetArgsStruct<
    AddInstructionInstructionArgs & {
        instructionDiscriminator: number[] /* size: 8 */;
    }
>(
    [
        ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
        ['incomingInstruction', incomingInstructionBeet]
    ],
    'AddInstructionInstructionArgs'
);
/**
 * Accounts required by the _addInstruction_ instruction
 *
 * @property [] multisig
 * @property [_writable_] transaction
 * @property [_writable_] instruction
 * @property [_writable_, **signer**] creator
 * @category Instructions
 * @category AddInstruction
 * @category generated
 */
export type AddInstructionInstructionAccounts = {
    multisig: web3.PublicKey;
    transaction: web3.PublicKey;
    instruction: web3.PublicKey;
    creator: web3.PublicKey;
    systemProgram?: web3.PublicKey;
    anchorRemainingAccounts?: web3.AccountMeta[];
};

export const addInstructionInstructionDiscriminator = [11, 70, 136, 166, 202, 55, 246, 74];

/**
 * Creates a _AddInstruction_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category AddInstruction
 * @category generated
 */
export function createAddInstructionInstruction(
    accounts: AddInstructionInstructionAccounts,
    args: AddInstructionInstructionArgs,
    programId = new web3.PublicKey('SMPLecH534NA9acpos4G6x7uf3LWbCAwZQE9e8ZekMu')
) {
    const [data] = addInstructionStruct.serialize({
        instructionDiscriminator: addInstructionInstructionDiscriminator,
        ...args
    });
    const keys: web3.AccountMeta[] = [
        {
            pubkey: accounts.multisig,
            isWritable: false,
            isSigner: false
        },
        {
            pubkey: accounts.transaction,
            isWritable: true,
            isSigner: false
        },
        {
            pubkey: accounts.instruction,
            isWritable: true,
            isSigner: false
        },
        {
            pubkey: accounts.creator,
            isWritable: true,
            isSigner: true
        },
        {
            pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
            isWritable: false,
            isSigner: false
        }
    ];

    if (accounts.anchorRemainingAccounts != null) {
        for (const acc of accounts.anchorRemainingAccounts) {
            keys.push(acc);
        }
    }

    const ix = new web3.TransactionInstruction({
        programId,
        keys,
        data
    });
    return ix;
}
