/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from "@metaplex-foundation/beet";
import * as web3 from "@solana/web3.js";

/**
 * @category Instructions
 * @category ChangeThreshold
 * @category generated
 */
export type ChangeThresholdInstructionArgs = {
  newThreshold: number;
};
/**
 * @category Instructions
 * @category ChangeThreshold
 * @category generated
 */
export const changeThresholdStruct = new beet.BeetArgsStruct<
  ChangeThresholdInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */;
  }
>(
  [
    ["instructionDiscriminator", beet.uniformFixedSizeArray(beet.u8, 8)],
    ["newThreshold", beet.u16],
  ],
  "ChangeThresholdInstructionArgs"
);
/**
 * Accounts required by the _changeThreshold_ instruction
 *
 * @property [_writable_] multisig
 * @property [_writable_, **signer**] multisigAuth
 * @category Instructions
 * @category ChangeThreshold
 * @category generated
 */
export type ChangeThresholdInstructionAccounts = {
  multisig: web3.PublicKey;
  multisigAuth: web3.PublicKey;
  anchorRemainingAccounts?: web3.AccountMeta[];
};

export const changeThresholdInstructionDiscriminator = [
  146, 151, 213, 63, 121, 79, 9, 29,
];

/**
 * Creates a _ChangeThreshold_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category ChangeThreshold
 * @category generated
 */
export function createChangeThresholdInstruction(
  accounts: ChangeThresholdInstructionAccounts,
  args: ChangeThresholdInstructionArgs,
  programId = new web3.PublicKey("SMPLecH534NA9acpos4G6x7uf3LWbCAwZQE9e8ZekMu")
) {
  const [data] = changeThresholdStruct.serialize({
    instructionDiscriminator: changeThresholdInstructionDiscriminator,
    ...args,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.multisig,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.multisigAuth,
      isWritable: true,
      isSigner: true,
    },
  ];

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc);
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
