/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from "@metaplex-foundation/beet";
import * as web3 from "@solana/web3.js";

/**
 * @category Instructions
 * @category ExecuteInstruction
 * @category generated
 */
export const executeInstructionStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */;
}>(
  [["instructionDiscriminator", beet.uniformFixedSizeArray(beet.u8, 8)]],
  "ExecuteInstructionInstructionArgs"
);
/**
 * Accounts required by the _executeInstruction_ instruction
 *
 * @property [_writable_] multisig
 * @property [_writable_] transaction
 * @property [_writable_] instruction
 * @property [_writable_, **signer**] member
 * @category Instructions
 * @category ExecuteInstruction
 * @category generated
 */
export type ExecuteInstructionInstructionAccounts = {
  multisig: web3.PublicKey;
  transaction: web3.PublicKey;
  instruction: web3.PublicKey;
  member: web3.PublicKey;
  anchorRemainingAccounts?: web3.AccountMeta[];
};

export const executeInstructionInstructionDiscriminator = [
  48, 18, 40, 40, 75, 74, 147, 110,
];

/**
 * Creates a _ExecuteInstruction_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category ExecuteInstruction
 * @category generated
 */
export function createExecuteInstructionInstruction(
  accounts: ExecuteInstructionInstructionAccounts,
  programId = new web3.PublicKey("SMPLecH534NA9acpos4G6x7uf3LWbCAwZQE9e8ZekMu")
) {
  const [data] = executeInstructionStruct.serialize({
    instructionDiscriminator: executeInstructionInstructionDiscriminator,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.multisig,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.transaction,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.instruction,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.member,
      isWritable: true,
      isSigner: true,
    },
  ];

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc);
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
