/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from "@solana/web3.js";
import * as beetSolana from "@metaplex-foundation/beet-solana";
import * as beet from "@metaplex-foundation/beet";

/**
 * @category Instructions
 * @category RemoveMember
 * @category generated
 */
export type RemoveMemberInstructionArgs = {
  oldMember: web3.PublicKey;
};
/**
 * @category Instructions
 * @category RemoveMember
 * @category generated
 */
export const removeMemberStruct = new beet.BeetArgsStruct<
  RemoveMemberInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */;
  }
>(
  [
    ["instructionDiscriminator", beet.uniformFixedSizeArray(beet.u8, 8)],
    ["oldMember", beetSolana.publicKey],
  ],
  "RemoveMemberInstructionArgs"
);
/**
 * Accounts required by the _removeMember_ instruction
 *
 * @property [_writable_] multisig
 * @property [_writable_, **signer**] multisigAuth
 * @category Instructions
 * @category RemoveMember
 * @category generated
 */
export type RemoveMemberInstructionAccounts = {
  multisig: web3.PublicKey;
  multisigAuth: web3.PublicKey;
  anchorRemainingAccounts?: web3.AccountMeta[];
};

export const removeMemberInstructionDiscriminator = [
  171, 57, 231, 150, 167, 128, 18, 55,
];

/**
 * Creates a _RemoveMember_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category RemoveMember
 * @category generated
 */
export function createRemoveMemberInstruction(
  accounts: RemoveMemberInstructionAccounts,
  args: RemoveMemberInstructionArgs,
  programId = new web3.PublicKey("SMPLecH534NA9acpos4G6x7uf3LWbCAwZQE9e8ZekMu")
) {
  const [data] = removeMemberStruct.serialize({
    instructionDiscriminator: removeMemberInstructionDiscriminator,
    ...args,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.multisig,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.multisigAuth,
      isWritable: true,
      isSigner: true,
    },
  ];

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc);
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
