/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from "@solana/web3.js";
import * as beetSolana from "@metaplex-foundation/beet-solana";
import * as beet from "@metaplex-foundation/beet";

/**
 * @category Instructions
 * @category RemoveMemberAndChangeThreshold
 * @category generated
 */
export type RemoveMemberAndChangeThresholdInstructionArgs = {
  oldMember: web3.PublicKey;
  newThreshold: number;
};
/**
 * @category Instructions
 * @category RemoveMemberAndChangeThreshold
 * @category generated
 */
export const removeMemberAndChangeThresholdStruct = new beet.BeetArgsStruct<
  RemoveMemberAndChangeThresholdInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */;
  }
>(
  [
    ["instructionDiscriminator", beet.uniformFixedSizeArray(beet.u8, 8)],
    ["oldMember", beetSolana.publicKey],
    ["newThreshold", beet.u16],
  ],
  "RemoveMemberAndChangeThresholdInstructionArgs"
);
/**
 * Accounts required by the _removeMemberAndChangeThreshold_ instruction
 *
 * @property [_writable_] multisig
 * @property [_writable_, **signer**] multisigAuth
 * @category Instructions
 * @category RemoveMemberAndChangeThreshold
 * @category generated
 */
export type RemoveMemberAndChangeThresholdInstructionAccounts = {
  multisig: web3.PublicKey;
  multisigAuth: web3.PublicKey;
  anchorRemainingAccounts?: web3.AccountMeta[];
};

export const removeMemberAndChangeThresholdInstructionDiscriminator = [
  230, 97, 183, 248, 43, 190, 154, 29,
];

/**
 * Creates a _RemoveMemberAndChangeThreshold_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category RemoveMemberAndChangeThreshold
 * @category generated
 */
export function createRemoveMemberAndChangeThresholdInstruction(
  accounts: RemoveMemberAndChangeThresholdInstructionAccounts,
  args: RemoveMemberAndChangeThresholdInstructionArgs,
  programId = new web3.PublicKey("SMPLecH534NA9acpos4G6x7uf3LWbCAwZQE9e8ZekMu")
) {
  const [data] = removeMemberAndChangeThresholdStruct.serialize({
    instructionDiscriminator:
      removeMemberAndChangeThresholdInstructionDiscriminator,
    ...args,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.multisig,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.multisigAuth,
      isWritable: true,
      isSigner: true,
    },
  ];

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc);
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
