/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from "@metaplex-foundation/beet";
import * as web3 from "@solana/web3.js";

/**
 * @category Instructions
 * @category SetExternalExecute
 * @category generated
 */
export type SetExternalExecuteInstructionArgs = {
  setting: boolean;
};
/**
 * @category Instructions
 * @category SetExternalExecute
 * @category generated
 */
export const setExternalExecuteStruct = new beet.BeetArgsStruct<
  SetExternalExecuteInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */;
  }
>(
  [
    ["instructionDiscriminator", beet.uniformFixedSizeArray(beet.u8, 8)],
    ["setting", beet.bool],
  ],
  "SetExternalExecuteInstructionArgs"
);
/**
 * Accounts required by the _setExternalExecute_ instruction
 *
 * @property [_writable_] multisig
 * @property [_writable_, **signer**] multisigAuth
 * @category Instructions
 * @category SetExternalExecute
 * @category generated
 */
export type SetExternalExecuteInstructionAccounts = {
  multisig: web3.PublicKey;
  multisigAuth: web3.PublicKey;
  anchorRemainingAccounts?: web3.AccountMeta[];
};

export const setExternalExecuteInstructionDiscriminator = [
  28, 57, 161, 204, 253, 3, 18, 183,
];

/**
 * Creates a _SetExternalExecute_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category SetExternalExecute
 * @category generated
 */
export function createSetExternalExecuteInstruction(
  accounts: SetExternalExecuteInstructionAccounts,
  args: SetExternalExecuteInstructionArgs,
  programId = new web3.PublicKey("SMPLecH534NA9acpos4G6x7uf3LWbCAwZQE9e8ZekMu")
) {
  const [data] = setExternalExecuteStruct.serialize({
    instructionDiscriminator: setExternalExecuteInstructionDiscriminator,
    ...args,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.multisig,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.multisigAuth,
      isWritable: true,
      isSigner: true,
    },
  ];

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc);
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
